name: Scheduled Workflow
on:
  push: [main]
  schedule:
    - cron: '*/1 * * * *'
  # Optional: allows manual triggering for testing
  workflow_dispatch: 

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Executing scheduled task..."
